require('./bootstrap');
// require('./components/navbar');
// require('./components/dropdowns');
require('./components/charts');
require('./components/Chart.extension');
// require('./components/highlight');
// require('./components/tooltip');
// require('./components/dropzone');
require('./components/select2');
require('./components/wizard');
require('./components/list');
// require('./components/quill.js');
// require('./main.js');
